version: '3.3'

services:

  test:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: ${IMAGE:-pipdevs/app}
    environment:
      - SOCKET_IO_ENABLED=true
    ports:
      - "8080:8080"
