---
# Container descriptor
- descriptor: "pip-services:context-info:default:default:1.0"
  name: "service-pushnotifications"
  description: "Push notifications microservice for pip-services"

# Console logger
- descriptor: "pip-services:logger:console:default:1.0"
  level: "trace"

# Performance counters that posts values to log
- descriptor: "pip-services:counters:log:default:1.0"
  level: "trace"

{{#if SOCKET_IO_ENABLED}}
# Socket IO connector
- descriptor: "service-pushnotifications:connector:socketio:default:1.0"
{{/if}}

{{#unless SOCKET_IO_ENABLED}}
# Default null connector
- descriptor: "service-pushnotifications:connector:null:default:1.0"
{{/unless}}

# Default controller
- descriptor: "service-pushnotifications:controller:default:default:1.0"

# Common HTTP endpoint
- descriptor: "pip-services:endpoint:http:default:1.0"
  connection:
    protocol: "http"
    host: "0.0.0.0"
    port: 8080

# HTTP endpoint version 1.0
- descriptor: "service-pushnotifications:service:http:default:1.0"
  swagger:
    enable: true
    auto: true

# Heartbeat service
- descriptor: "pip-services:heartbeat-service:http:default:1.0"

# Status service
- descriptor: "pip-services:status-service:http:default:1.0"

# Swagger service
- descriptor: "pip-services:swagger-service:http:default:1.0"
